# Generated by Django 5.0.6 on 2024-05-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sortname", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=150)),
                ("phonecode", models.IntegerField()),
            ],
            options={"db_table": "cities",},
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sortname", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=150)),
                ("phonecode", models.IntegerField()),
            ],
            options={"db_table": "states",},
        ),
        migrations.CreateModel(
            name="tblPromoCode",
            fields=[
                ("PromoCode_Id", models.AutoField(primary_key=True, serialize=False)),
                ("PromoCode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "PromoCodeType",
                    models.IntegerField(db_comment="1=> Percentage, 2=> Fixed Amount"),
                ),
                ("PromoCodeValue", models.FloatField(blank=True, null=True)),
                ("PromoCodeValidFrom", models.IntegerField(blank=True, null=True)),
                ("PromoCodeValidUpTo", models.IntegerField(blank=True, null=True)),
                (
                    "PromoCodeValidFor",
                    models.IntegerField(
                        db_comment="0=>Invalid, 1=> All, 2=> All ChannelPartner, 3=> All Members, 4=>Specified ChannelPartner, 4=> Specified Members"
                    ),
                ),
                ("PromoCodeValidCount", models.IntegerField(blank=True, null=True)),
                ("PromoCodeUsageCount", models.IntegerField(blank=True, null=True)),
                (
                    "PromoCodeStatus",
                    models.IntegerField(
                        db_comment="0=> Unpublished, 1=>Active, 2=> Expired, 3=> Utilized, 4=> Deactive"
                    ),
                ),
                ("PromoCodeCreatedOn", models.IntegerField(blank=True, null=True)),
                (
                    "PromoCodeBannerImagePath",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "tblPromoCode",},
        ),
        migrations.CreateModel(
            name="tblGoldBookingDetails",
            fields=[
                ("GBAccountId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "GBAccountDisplayId",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("GBRate", models.FloatField(blank=True, null=True)),
                ("GBWeight", models.FloatField(blank=True, null=True)),
                ("GBTennure", models.IntegerField(blank=True, null=True)),
                (
                    "GBProcessinChargesApplicable",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "GBProcessingChargeDisocunt",
                    models.FloatField(blank=True, null=True),
                ),
                ("GBProcessingCharge", models.FloatField(blank=True, null=True)),
                ("GBProcessingChargeGST", models.FloatField(blank=True, null=True)),
                ("GBProcessingChargePayable", models.FloatField(blank=True, null=True)),
                (
                    "GBBookingChargesApplicable",
                    models.FloatField(blank=True, null=True),
                ),
                ("GBBookingChargeDisocunt", models.FloatField(blank=True, null=True)),
                ("GBBookingCharge", models.FloatField(blank=True, null=True)),
                ("GBBookingChargeGST", models.FloatField(blank=True, null=True)),
                ("GBBookingChargePayable", models.FloatField(blank=True, null=True)),
                ("GBDownPayment", models.FloatField(blank=True, null=True)),
                ("GBFixTennure", models.IntegerField(db_comment="0: No 1: Yes")),
                ("GBFixTennureDiscount", models.FloatField(blank=True, null=True)),
                ("GBBookingAmount", models.FloatField(blank=True, null=True)),
                ("GBMonthlyInstallment", models.FloatField(blank=True, null=True)),
                (
                    "GBAccountStatus",
                    models.IntegerField(
                        db_comment="0: Added 1: Approved 2: Closed 3: Cancelled 4: Rejected"
                    ),
                ),
                ("GDRStatusOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "GBPromoCodeId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GBPromoCodeId",
                        to="api.tblpromocode",
                    ),
                ),
            ],
            options={"db_table": "tblGoldBookingDetails",},
        ),
        migrations.CreateModel(
            name="tblUsers",
            fields=[
                ("User_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "UserFirstname",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "UserMiddlename",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "UserLastname",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "UserCompnayName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "UserPannumber",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "UserAadharNumber",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "UserGSTNumber",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("UserMobileNo", models.BigIntegerField(blank=True, null=True)),
                ("UseralternateNo", models.BigIntegerField(blank=True, null=True)),
                ("UserEmail", models.CharField(blank=True, max_length=100, null=True)),
                ("UserDateofBirth", models.IntegerField(blank=True, null=True)),
                ("UserAnniversaryDate", models.IntegerField(blank=True, null=True)),
                (
                    "UserQRCodeImage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "UserGender",
                    models.IntegerField(
                        blank=True, db_comment="1=>Male, 2=>Female", null=True
                    ),
                ),
                (
                    "UserMarritalStatus",
                    models.IntegerField(
                        blank=True,
                        db_comment="1=>Single, 2=>Married, 3=>Widow, 4=>Divorcy",
                        null=True,
                    ),
                ),
                (
                    "UserRole",
                    models.IntegerField(
                        blank=True,
                        db_comment="0=>Super Admin, 1=>Admin, 2=>Manager, 3=>Supervisor, 4=>Account, 5=> ChannelPartner, 6=> Member",
                        null=True,
                    ),
                ),
                (
                    "UserChannelPartnerCode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("UserChannelPartnerOn", models.IntegerField(blank=True, null=True)),
                (
                    "UserPassword",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "UserStatus",
                    models.IntegerField(
                        db_comment="1=>Active, 0=>Deactive,2=>Blocked "
                    ),
                ),
                (
                    "UserAddress",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("UserPincode", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "UserReferanceCode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "UserParrentId",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("UserAddedOn", models.IntegerField(blank=True, null=True)),
                (
                    "UserCityId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cities",
                    ),
                ),
                (
                    "UserCountryId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.countries",
                    ),
                ),
                (
                    "UserStateId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.states",
                    ),
                ),
            ],
            options={"db_table": "tblUsers",},
        ),
        migrations.CreateModel(
            name="tblUserLoanDetails",
            fields=[
                ("UserLoan_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "LRTransactionId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("LRAmount", models.FloatField(blank=True, null=True)),
                ("LRStatus", models.IntegerField(blank=True, null=True)),
                ("LRStatusOn", models.IntegerField(blank=True, null=True)),
                ("LRComment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "LRAdminRemark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "LRPaymentMethod",
                    models.IntegerField(
                        db_comment="1: Cash, 2: Cheque, 3: BankTransfer, 4: UPI"
                    ),
                ),
                (
                    "LRPaymentDetails",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "LRTransactionDetails",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("LRTransactionOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserLoanDetails_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserLoanDetails_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LRUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="LRUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserLoanDetails_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblUserLoanDetails",},
        ),
        migrations.CreateModel(
            name="tblUserDocuments",
            fields=[
                (
                    "UserDocument_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "UserDocumentType",
                    models.IntegerField(
                        db_comment="1: Profile, 2: PAN, 3: Aadhar, 4: Address"
                    ),
                ),
                (
                    "UserDocumentURL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "UserDocumentBackURL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDocuments_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDocuments_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDocuments_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblUserDocuments",},
        ),
        migrations.CreateModel(
            name="tblUserDevices",
            fields=[
                ("UserDevice_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "UserDeviceDetails",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "UserDeviceToken",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "UserDeviceStatus",
                    models.IntegerField(db_comment="1:Active 2:Deactive 3: Blocked"),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDevices_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDevices_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserDevices_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="UserId",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblUserDevices",},
        ),
        migrations.CreateModel(
            name="tblUserActions",
            fields=[
                ("UserAction_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "UserActionUserId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "UserActionFor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("UserActionOn", models.IntegerField(blank=True, null=True)),
                (
                    "UserActionRequestData",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "UserActionResponseData",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserActions_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserActions_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblUserActions_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblUserActions",},
        ),
        migrations.CreateModel(
            name="tblSystemParameters",
            fields=[
                (
                    "SystemParameter_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "SystemParameterName",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "SystemParameterValue",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "SystemParameterUpdatedOn",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "SystemParameterActiveYN",
                    models.IntegerField(db_comment="0 for Not Active, 1 for Active"),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblSystemParameters_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblSystemParameters_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblSystemParameters_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "SystemParameterUpdatedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblSystemParameters",},
        ),
        migrations.CreateModel(
            name="tblReferedLink",
            fields=[
                ("ReferedLink_Id", models.AutoField(primary_key=True, serialize=False)),
                ("ReferedName", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ReferedMobileNo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "ReferedEmail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblReferedLink_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblReferedLink_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblReferedLink_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "ReferedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblReferedLink",},
        ),
        migrations.CreateModel(
            name="tblPromoCodeUsages",
            fields=[
                (
                    "PromoCodeusage_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("PromoCodeUsageOn", models.IntegerField(blank=True, null=True)),
                (
                    "PromoCodeUsageStatus",
                    models.IntegerField(db_comment="1:Accepted 2: Rejected"),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "PromoCodeId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblpromocode",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblPromoCodeUsages_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblPromoCodeUsages_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblPromoCodeUsages_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "PromoCodeUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblPromoCodeUsages",},
        ),
        migrations.AddField(
            model_name="tblpromocode",
            name="CreatedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblPromoCode_CreatedBy",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblpromocode",
            name="DeletedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblPromoCode_DeletedBy",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblpromocode",
            name="LastModifiedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblPromoCode_LastModifiedBy",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblpromocode",
            name="PromoCode_CreatedByUserId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tblusers",
            ),
        ),
        migrations.CreateModel(
            name="tblNomineeDetails",
            fields=[
                ("Nominee_Id", models.AutoField(primary_key=True, serialize=False)),
                ("NomineeForAccountId", models.IntegerField(blank=True, null=True)),
                (
                    "NomieeForAccountType",
                    models.IntegerField(db_comment="1: Booking, 2: Deposite"),
                ),
                (
                    "NomineeFirstName",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "NomieeLastname",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "NomieeMobileNo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "NomieeEmail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "NomieeRelation",
                    models.IntegerField(
                        db_comment="1: Wife, 2: Mother, 3: Father, 4: Daughter ,5: Son ,6: Brother, 7: Sister ,8: Friend, 9: SecondRelative,  10: Other"
                    ),
                ),
                ("NomieeDateofBirth", models.IntegerField(blank=True, null=True)),
                (
                    "NomieeIsMinorYN",
                    models.IntegerField(db_comment="0: Not Minor 1: Minor"),
                ),
                (
                    "NomieeStatus",
                    models.IntegerField(
                        db_comment="0: Added, 1: Approved, 2: Rejected"
                    ),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblNomineeDetails_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblNomineeDetails_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblNomineeDetails_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "NomieeForUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblNomineeDetails",},
        ),
        migrations.CreateModel(
            name="tblMatuniryRateChart",
            fields=[
                ("RateChart_Id", models.AutoField(primary_key=True, serialize=False)),
                ("RateChartStartValue", models.IntegerField(blank=True, null=True)),
                ("RateChartEndValue", models.IntegerField(blank=True, null=True)),
                ("RateChartBankYesValue", models.IntegerField(blank=True, null=True)),
                ("RateChartBankNoValue", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblMatuniryRateChart_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblMatuniryRateChart_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblMatuniryRateChart_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblMatuniryRateChart",},
        ),
        migrations.CreateModel(
            name="tblLoanRequests",
            fields=[
                ("LoanRequestId", models.AutoField(primary_key=True, serialize=False)),
                ("LRAmount", models.FloatField(blank=True, null=True)),
                ("LRComment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "LRAdminRemark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("LRAdminStatus", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblLoanRequests_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblLoanRequests_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LRUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="LRUser_Id",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblLoanRequests_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblLoanRequests",},
        ),
        migrations.CreateModel(
            name="tblGoldBookingTransactions",
            fields=[
                ("GBT_Id", models.AutoField(primary_key=True, serialize=False)),
                ("GBTInstallmentAmount", models.FloatField(blank=True, null=True)),
                ("GBTPeriod", models.IntegerField(blank=True, null=True)),
                ("GBTCreditAmount", models.FloatField(blank=True, null=True)),
                ("GBTRemaining_Amount", models.FloatField(blank=True, null=True)),
                ("GBTDebitAmount", models.FloatField(blank=True, null=True)),
                ("GBTComment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "GBTEntryType",
                    models.IntegerField(
                        db_comment="1: Installment, 2: Credit, 3: Debit"
                    ),
                ),
                (
                    "GBTTransactionId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("GBTWalletPay", models.IntegerField(db_comment="0: No, 1: Yes")),
                (
                    "GBTPaymentMethod",
                    models.IntegerField(
                        db_comment="1: Cash, 2: Cheque, 3: BankTransfer, 4: UPI"
                    ),
                ),
                (
                    "GBTPaymentDetails",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("GBTTransactionOn", models.FloatField(blank=True, null=True)),
                (
                    "GBTStatus",
                    models.IntegerField(
                        db_comment="0:Inserted 1: Paid 2: Approved 3: Rejected 4: Failed"
                    ),
                ),
                ("GBTStatusOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "GBT_AccountId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GBT_AccountId",
                        to="api.tblgoldbookingdetails",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingTransactions_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingTransactions_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GBTStatusByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GBTStatusByUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GBTUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GBTUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingTransactions_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblGoldBookingTransactions",},
        ),
        migrations.CreateModel(
            name="tblGoldBookingDiscountChart",
            fields=[
                (
                    "DiscountChart_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "DiscountChartTennueValue",
                    models.IntegerField(blank=True, null=True),
                ),
                ("DiscountChartQuantity", models.IntegerField(blank=True, null=True)),
                ("DiscountChartAmount", models.IntegerField(blank=True, null=True)),
                ("DiscountChartUpdatedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingDiscountChart_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingDiscountChart_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DicsountChartUpdatedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldBookingDiscountChart_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblGoldBookingDiscountChart",},
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="CreatedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblGoldBookingDetails_CreatedBy",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="DeletedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblGoldBookingDetails_DeletedBy",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="GBChannelPartnerUserId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="GBChannelPartnerUserId",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="GBUserId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="GBUserId",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="GDRStatusByUserId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="GDRStatusByUserId",
                to="api.tblusers",
            ),
        ),
        migrations.AddField(
            model_name="tblgoldbookingdetails",
            name="LastModifiedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tblGoldBookingDetails_LastModifiedBy",
                to="api.tblusers",
            ),
        ),
        migrations.CreateModel(
            name="tblDepositDocuments",
            fields=[
                (
                    "DepositDocument_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "DepositDocumentAccountId",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "DepositDocumentURL",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("DepositDocumentAddedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblDepositDocuments_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblDepositDocuments_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DepositUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblDepositDocuments_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblDepositDocuments",},
        ),
        migrations.CreateModel(
            name="tblChannelPartnerSlabs",
            fields=[
                ("CPS_Id", models.AutoField(primary_key=True, serialize=False)),
                ("CPSLimitStart", models.IntegerField(blank=True, null=True)),
                ("CPSLimitEnd", models.IntegerField(blank=True, null=True)),
                ("CPSMethod", models.IntegerField(blank=True, null=True)),
                (
                    "CPSCommissionType",
                    models.IntegerField(db_comment="1: Percentage ,2: Fixed"),
                ),
                ("CPSCommisionValue", models.IntegerField(blank=True, null=True)),
                ("CPSCommisionAddedOn", models.IntegerField(blank=True, null=True)),
                ("CPSCommissionUpdatedon", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CPSCommissionAddedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_channel_partner_slabs",
                        to="api.tblusers",
                    ),
                ),
                (
                    "CPSCommissionUpdatedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_channel_partner_slabs",
                        to="api.tblusers",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerSlabs_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerSlabs_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerSlabs_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblChannelPartnerSlabs",},
        ),
        migrations.CreateModel(
            name="tblChannelPartnerRequests",
            fields=[
                ("CPRequest_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CPStatus",
                    models.IntegerField(db_comment="1: Requested ,2: Approved"),
                ),
                ("CPRequestOn", models.IntegerField(blank=True, null=True)),
                ("CPRequestAdminUpdatedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CPUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerRequests_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerRequests_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerRequests_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblChannelPartnerRequests",},
        ),
        migrations.CreateModel(
            name="tblChannelPartnerPayouts",
            fields=[
                ("CPP_Id", models.AutoField(primary_key=True, serialize=False)),
                ("CPPPayoutId", models.CharField(blank=True, max_length=10, null=True)),
                ("CPPGold", models.IntegerField(blank=True, null=True)),
                ("CPPPaidAmount", models.FloatField(blank=True, null=True)),
                ("CPPForMonthYear", models.IntegerField(blank=True, null=True)),
                (
                    "CPPPayoutRemark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "CPPPayoutStatus",
                    models.IntegerField(db_comment="1: Percentage ,2: Fixed"),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CPPPayoutApprovedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="CPPPayoutApprovedByUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "CPPUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="CPPUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerPayouts_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerPayouts_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblChannelPartnerPayouts_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblChannelPartnerPayouts",},
        ),
        migrations.CreateModel(
            name="tblBankDetails",
            fields=[
                ("BankDetails_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "BankDetailsName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "BankDetailsBankName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "BankDetailsAccountNo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "BankDetailsIFSC",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "BankDetailsBranch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "BankDetailsAccountType",
                    models.IntegerField(db_comment="1: Saving 2: Current"),
                ),
                (
                    "BankDetailsStatus",
                    models.IntegerField(db_comment="0: Added, 1: Approved 2: Rejected"),
                ),
                ("BankDetailsAddedOn", models.IntegerField(blank=True, null=True)),
                ("BankDetailsUpdatedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "BankDetailsAddedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BankDetailsAddedByUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "BankDetailsUpdatedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BankDetailsUpdatedByUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "BankDetails_UserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BankDetails_UserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblBankDetails_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblBankDetails_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblBankDetails_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblBankDetails",},
        ),
        migrations.CreateModel(
            name="Rates",
            fields=[
                ("Rate_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Rate_Purchase", models.FloatField(blank=True, null=True)),
                ("Rate_Sales", models.FloatField(blank=True, null=True)),
                ("Rate_UpdatedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Rates_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Rates_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Rates_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "Rate_UpdatedByUserid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "Rates",},
        ),
        migrations.CreateModel(
            name="tblVendors",
            fields=[
                ("VendorId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Vendor_Name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "VendorLetterPathURL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "VendorLogoPathURL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "VendoradvertisementPathURL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "VendorStatus",
                    models.IntegerField(db_comment="0: Not Active 1: Active"),
                ),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblVendors_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblVendors_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblVendors_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
            ],
            options={"db_table": "tblVendors",},
        ),
        migrations.CreateModel(
            name="tblGoldDepositeRequests",
            fields=[
                ("GDRAccountId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "GDRAccountDisplayId",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("GDRDepositeGold", models.FloatField(blank=True, null=True)),
                (
                    "GDRProcessingChargeApplicable",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "GDRProcessingChargeDisocunt",
                    models.FloatField(blank=True, null=True),
                ),
                ("GDRProcessingCharge", models.FloatField(blank=True, null=True)),
                ("GDRProcessingChargeGST", models.FloatField(blank=True, null=True)),
                (
                    "GDRProcessingChargePayable",
                    models.FloatField(blank=True, null=True),
                ),
                ("GDRTennure", models.IntegerField(blank=True, null=True)),
                ("GDRGoldRate", models.FloatField(blank=True, null=True)),
                ("GDRGoldAmount", models.FloatField(blank=True, null=True)),
                (
                    "GDRStatus",
                    models.IntegerField(
                        db_comment="0: Deposited, 1: Approved, 2: Closed, 3: Canceled, 4: Rejected"
                    ),
                ),
                ("GDRStatusOn", models.IntegerField(blank=True, null=True)),
                ("GDRMaturityWeight", models.FloatField(blank=True, null=True)),
                ("GDRMaturityDate", models.IntegerField(blank=True, null=True)),
                ("GDRBankGuranteeYN", models.IntegerField(db_comment="1: Yes 0: No")),
                ("GDRRemarks", models.CharField(blank=True, max_length=255, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "GDRPromoCodeId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDRPromoCodeId",
                        to="api.tblpromocode",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDepositeRequests_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDepositeRequests_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDRChannelPartherId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDRChannelPartherId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDRStatusByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gold_deposite_requests_status_user",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDRUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDRUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDepositeRequests_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDRVendorId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDRVendorId",
                        to="api.tblvendors",
                    ),
                ),
            ],
            options={"db_table": "tblGoldDepositeRequests",},
        ),
        migrations.CreateModel(
            name="tblGoldDelivery",
            fields=[
                (
                    "GoldDelivery_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "GDAccountType",
                    models.IntegerField(db_comment="1: Booking, 2: Deposit"),
                ),
                (
                    "GDTransactionId",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "GDBankDetailsName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "GDBankDetailsBankName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "GDBankDetailsAccountNo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "GDBankDetailsIFSC",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "GDBankDetailsBranch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "GDBankDetailsAccountType",
                    models.IntegerField(db_comment="1: Saving 2: Current"),
                ),
                ("GDAmount", models.FloatField(blank=True, null=True)),
                ("GDComment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "GDStatus",
                    models.IntegerField(
                        db_comment="0: Requsted 1: Approved, 2: Rejected"
                    ),
                ),
                ("GDRequestedOn", models.IntegerField(blank=True, null=True)),
                ("GDApprovedOn", models.IntegerField(blank=True, null=True)),
                ("CreatedOn", models.IntegerField(blank=True, null=True)),
                ("LastModifiedOn", models.IntegerField(blank=True, null=True)),
                ("IsDeleted", models.IntegerField(default=0)),
                ("DeletedOn", models.IntegerField(blank=True, null=True)),
                (
                    "GDAccountId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDAccountId",
                        to="api.tblgoldbookingdetails",
                    ),
                ),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDelivery_CreatedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "DeletedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDelivery_DeletedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDApprovedByUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDApprovedByUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDUserId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="GDUserId",
                        to="api.tblusers",
                    ),
                ),
                (
                    "LastModifiedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblGoldDelivery_LastModifiedBy",
                        to="api.tblusers",
                    ),
                ),
                (
                    "GDVendorId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tblVendors",
                        to="api.tblvendors",
                    ),
                ),
            ],
            options={"db_table": "tblGoldDelivery",},
        ),
    ]
